apiVersion: apps/v1
kind: Deployment
metadata:
  name: papertechtrend
  labels:
    app: papertechtrend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papertechtrend
  template:
    metadata:
      labels:
        app: papertechtrend
    spec:
      containers:
        - name: papertechtrend
          image: raminicano/ptt
          ports:
            - containerPort: 8000
            - containerPort: 8500
          env:
            - name: FASTAPI_URL1
              valueFrom:
                secretKeyRef:
                  name: papertechtrend-secrets
                  key: FASTAPI_URL1
            - name: FASTAPI_URL2
              valueFrom:
                secretKeyRef:
                  name: papertechtrend-secrets
                  key: FASTAPI_URL2
            - name: PORT1
              valueFrom:
                secretKeyRef:
                  name: papertechtrend-secrets
                  key: PORT1
            - name: PORT2
              valueFrom:
                secretKeyRef:
                  name: papertechtrend-secrets
                  key: PORT2
            - name: NODE_URL1
              valueFrom:
                secretKeyRef:
                  name: papertechtrend-secrets
                  key: NODE_URL1
            - name: NODE_URL2
              valueFrom:
                secretKeyRef:
                  name: papertechtrend-secrets
                  key: NODE_URL2
            - name: DB_HOST
              value: "nginx-proxy"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: papertechtrend-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: papertechtrend-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: papertechtrend-secrets
                  key: DB_NAME
            - name: DB_PORT
              value: "3306"